services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/data/Audiobooks:/audiobooks
      - /mnt/data/Podcasts:/podcasts
      - /var/lib/docker/volumes/audiobookshelf/config:/config
      - /var/lib/docker/volumes/audiobookshelf/metadata:/metadata
    environment:
      - TZ=America/New_York
