services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    ports:
      - 8080:8080
    networks:
      - caddy
    labels:
      caddy: glance.vpnluci.duckdns.org
      caddy.reverse_proxy: "{{upstreams 8080}}"
